steps:
  - name: "Create VM"
    command: "vagrant up --provider virtualbox && npm install"
    timeout_in_minutes: 10
    env:
      DISPLAY: ":0"

  # Wait and make sure the VM was successfully created before proceeding.
  - wait

  - name: "Install dependencies"
    command: "vagrant ssh -c 'cd /home/vagrant/sync; npm install'"

  - name: "Build Infusion"
    command: "vagrant ssh -c 'cd /home/vagrant/sync; grunt clean stylus modulefiles:all pathMap:all copy:all copy:necessities uglify:all concat:all compress:all'"

  - name: "Run tests"
    command: "gruntttt tests"

  - name: "Destroy VM"
    command: "vagrant destroy -f"

